// This file is auto-generated by @hey-api/openapi-ts

export type CheckUsernameAvailableResponse = {
    username: string;
    available: boolean;
};

export type GetUsernameResponse = {
    username: string;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type RegisterRequest = {
    username: string;
    address: string;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type RegisterUsernameRegisterPostData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/register';
};

export type RegisterUsernameRegisterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterUsernameRegisterPostError = RegisterUsernameRegisterPostErrors[keyof RegisterUsernameRegisterPostErrors];

export type RegisterUsernameRegisterPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CheckUsernameAvailableAvailableGetData = {
    body?: never;
    path?: never;
    query: {
        username: string;
    };
    url: '/available';
};

export type CheckUsernameAvailableAvailableGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CheckUsernameAvailableAvailableGetError = CheckUsernameAvailableAvailableGetErrors[keyof CheckUsernameAvailableAvailableGetErrors];

export type CheckUsernameAvailableAvailableGetResponses = {
    /**
     * Successful Response
     */
    200: CheckUsernameAvailableResponse;
};

export type CheckUsernameAvailableAvailableGetResponse = CheckUsernameAvailableAvailableGetResponses[keyof CheckUsernameAvailableAvailableGetResponses];

export type GetUsernameAddressGetData = {
    body?: never;
    path: {
        address: string;
    };
    query?: never;
    url: '/{address}';
};

export type GetUsernameAddressGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUsernameAddressGetError = GetUsernameAddressGetErrors[keyof GetUsernameAddressGetErrors];

export type GetUsernameAddressGetResponses = {
    /**
     * Successful Response
     */
    200: GetUsernameResponse;
};

export type GetUsernameAddressGetResponse = GetUsernameAddressGetResponses[keyof GetUsernameAddressGetResponses];

export type ClientOptions = {
    baseURL: 'http://localhost:8000' | (string & {});
};