parserOptions:
  ecmaVersion: latest
  project: tsconfig.json

extends:
  - next/core-web-vitals
  - next/typescript
  - plugin:storybook/recommended
  - plugin:jsx-a11y/recommended

plugins:
  - perfectionist
  - jsx-a11y

rules:
  no-plusplus: [ "error", { "allowForLoopAfterthoughts": true } ]
  no-console: [ "warn", { allow: [ "error" ] } ]

  "@typescript-eslint/no-unused-vars":
    - warn
    - args: "all"
      argsIgnorePattern: "^_"
      varsIgnorePattern: "^_"
      caughtErrors: "all"
      caughtErrorsIgnorePattern: "^_"


  perfectionist/sort-imports: [ "warn", { internalPattern: [ '@/**' ], } ]

  # Accessibility rules
  jsx-a11y/alt-text: error
  jsx-a11y/aria-props: error
  jsx-a11y/aria-proptypes: error
  jsx-a11y/aria-unsupported-elements: error
  jsx-a11y/role-has-required-aria-props: error
  jsx-a11y/role-supports-aria-props: error
  jsx-a11y/no-redundant-roles: warn
  jsx-a11y/label-has-associated-control: error
