parserOptions:
  ecmaVersion: latest
  project: tsconfig.json

extends:
  - next/core-web-vitals
  - next/typescript
  - plugin:storybook/recommended

plugins:
  - perfectionist

rules:
  no-plusplus: [ "error", { "allowForLoopAfterthoughts": true } ]
  no-console: [ "warn", { allow: [ "error" ] } ]

  "@typescript-eslint/no-unused-vars":
    - warn
    - args: "all"
      argsIgnorePattern: "^_"
      varsIgnorePattern: "^_"
      caughtErrors: "all"
      caughtErrorsIgnorePattern: "^_"


  perfectionist/sort-imports: [ "warn", { internalPattern: [ '@/**' ], } ]
