name: Continuous Integration - Front

on:
  pull_request:
    paths:
      - 'front/**'
  push:
    paths:
      - 'front/**'


jobs:
  eslint-front:
    name: "ESLint: Front"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: yarn
          cache-dependency-path: "yarn.lock"
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run ESLint
        run: yarn lint

  jest-front:
    name: "Unit tests: Front"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: yarn
          cache-dependency-path: "yarn.lock"
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run tests
        run: yarn workspace front test

  build-front:
    name: "Build: Front"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: yarn
          cache-dependency-path: "yarn.lock"
      - uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/front/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('yarn.lock') }}-${{ hashFiles('front/**/*.ts', 'front/**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn workspace front build
        env:
          NEXT_PUBLIC_PRIVY_APP_ID: ${{ secrets.FRONT_NEXT_PUBLIC_PRIVY_APP_ID }}

      - name: Deploy preview on Aleph
        if: ${{ github.event_name == 'pull_request' }}
        uses: aleph-im/web3-hosting-action@v0.1.1
        with:
          path: 'front/out'

  build-storybook:
    name: "Build: Storybook"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: yarn
          cache-dependency-path: "yarn.lock"
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn workspace front storybook:build
