name: Continuous Integration

on:
  pull_request:
    paths:
      - 'front/**'


jobs:
  eslint-front:
    name: "ESLint: front"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: yarn
          cache-dependency-path: "yarn.lock"
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run ESLint
        run: yarn lint

  prettier-front:
    name: "Prettier: front"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: yarn
          cache-dependency-path: "yarn.lock"
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run Prettier
        run: yarn format:check

  jest-front:
    name: "Unit tests: front"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: yarn
          cache-dependency-path: "yarn.lock"
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run tests
        run: yarn test

  build-front:
    name: "Build: front"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: yarn
          cache-dependency-path: "yarn.lock"
      - uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/front/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('yarn.lock') }}-${{ hashFiles('front/**/*.ts', 'front/**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn build
        env:
          NEXT_PUBLIC_PRIVY_APP_ID: ${{ secrets.FRONT_NEXT_PUBLIC_PRIVY_APP_ID }}

  build-storybook:
    name: "Build: Storybook"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: yarn
          cache-dependency-path: "yarn.lock"
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn storybook:build
