name: Mirroring to Epitech repository

on:
  push:

jobs:
  push-to-mirror:
    name: Push to Epitech repository
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cloning to mirror
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ vars.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.SSH_EPITECH_MIRRORING_KEY }}
